# Generated by Django 4.2.30 on 2026-06-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类编码')),
            ],
            options={
                'verbose_name': '商品分类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='条形码')),
                ('specification', models.CharField(blank=True, max_length=100, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('safety_stock', models.IntegerField(default=10, verbose_name='安全库存')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'product',
            },
        ),
    ]
